/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentationLayer;

import dataLayer.E_Customer;
import dataLayer.E_Sale;
import dataLayer.E_SaleDetail;
import dataLayer.E_Toy;
import dataLayer.E_User;
import java.awt.Frame;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logicLayer.F_Sale;
import logicLayer.F_SaleDetail;
import logicLayer.F_Toy;

/**
 *
 * @author aleja
 */
public class DlgSale extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DlgSale.class.getName());
    
    private E_User loggedUser;
    private int selectedToyId = -1;
    private DefaultTableModel cart;
    
   /**
     * Creates new form FrmSale
     */
    public DlgSale(Frame parent, boolean modal, E_User loggedUser) {
        super(parent, modal);
        initComponents();
        
        this.loggedUser = loggedUser;
        txtWorker.setText(loggedUser.getFirstName() + " " + loggedUser.getLastName());
        
        // Establece la fecha actual en el campo
        LocalDate today = LocalDate.now();
        txtDate.setText(String.valueOf(today));
        
        cart = new DefaultTableModel();
        cart.addColumn("Toy ID");
        cart.addColumn("Description");
        cart.addColumn("Price");
        cart.addColumn("Quantity");
        cart.addColumn("ISV");
        cart.addColumn("Sub-Total");

        tblCart.setModel(cart); // Asigna el modelo a tu jTable
    }
    
    private void calculateTotals() {
        double subTotalGeneral = 0.0;
        double isvGeneral = 0.0;

        // Recorrer todas las filas de la tabla carrito
        for (int i = 0; i < tblCart.getRowCount(); i++) {
            // Obtenemos los valores de las columnas ISV (índice 4) y SubTotal (índice 5)
            double isvFila = Double.parseDouble(tblCart.getValueAt(i, 4).toString());
            double subTotalFila = Double.parseDouble(tblCart.getValueAt(i, 5).toString());

            isvGeneral += isvFila;
            subTotalGeneral += subTotalFila;
        }

        double totalPagar = subTotalGeneral + isvGeneral;

        // Actualizar los campos de texto en la parte inferior (suponiendo sus nombres)
        // Usamos String.format para dejarlo con 2 decimales
        txtSubtotal.setText(String.format("%.2f", subTotalGeneral));
        txtResultTax.setText(String.format("%.2f", isvGeneral));
        txtTotal.setText(String.format("%.2f", totalPagar));
    }
    
    private void resetSaleForm() {
        // 1. Limpiar campos de texto del encabezado
        txtCustomerCode.setText("");
        txtCustomer.setText(""); // Nombre del cliente
        txtBillNumber.setText("");

        // 2. Limpiar cajas de texto de los juguetes
        clearToyFields();
        selectedToyId = -1; // Resetear la variable global

        // 3. Vaciar la tabla (Carrito)
        cart.setRowCount(0); 

        // 4. Poner totales en 0
        calculateTotals(); 

        // Opcional: Actualizar la fecha a la de hoy por si se quedó abierto de un día a otro
        txtDate.setText(String.valueOf(java.time.LocalDate.now()));
    }
    
    private void clearToyFields()
    {
        txtToy.setText("");
        txtPrice.setText("");
        txtStock.setText("");
        txtQuantity.setText("");
        txtTax.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCustomerCode = new javax.swing.JTextField();
        txtCustomer = new javax.swing.JTextField();
        txtWorker = new javax.swing.JTextField();
        btnSearchCustomer = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCart = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();
        btnLeave = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtResultTax = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtToy = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        btnSearchToy = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTax = new javax.swing.JTextField();
        btnAddToy = new javax.swing.JButton();
        btnRemoveToy = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtBillNumber = new javax.swing.JTextField();
        imgSales1 = new logicLayer.ImgSales();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer Data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Customer:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Worker:");

        txtCustomerCode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCustomerCode.setEnabled(false);

        txtCustomer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCustomer.setEnabled(false);

        txtWorker.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtWorker.setEnabled(false);

        btnSearchCustomer.setBackground(new java.awt.Color(51, 51, 255));
        btnSearchCustomer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearchCustomer.setText(". . .");
        btnSearchCustomer.addActionListener(this::btnSearchCustomerActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCustomerCode, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtWorker)
                    .addComponent(txtCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCustomerCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchCustomer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtWorker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        tblCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCartMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCart);

        btnSave.setBackground(new java.awt.Color(51, 51, 255));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(this::btnSaveActionPerformed);

        btnLeave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLeave.setText("Leave");
        btnLeave.addActionListener(this::btnLeaveActionPerformed);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Sub-Total:");

        txtSubtotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSubtotal.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("ISV:");

        txtResultTax.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtResultTax.setEnabled(false);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Total:");

        txtTotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTotal.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtResultTax, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 952, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLeave, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLeave))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtResultTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Toy Data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Toy:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Price:");

        txtToy.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtToy.setEnabled(false);

        txtPrice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPrice.setEnabled(false);

        btnSearchToy.setBackground(new java.awt.Color(51, 51, 255));
        btnSearchToy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearchToy.setText(". . .");
        btnSearchToy.addActionListener(this::btnSearchToyActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Stock:");

        txtStock.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtStock.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Quantity:");

        txtQuantity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("ISV:");

        txtTax.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTax.setEnabled(false);

        btnAddToy.setBackground(new java.awt.Color(51, 51, 255));
        btnAddToy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddToy.setText("+");
        btnAddToy.setToolTipText("");
        btnAddToy.addActionListener(this::btnAddToyActionPerformed);

        btnRemoveToy.setBackground(new java.awt.Color(51, 51, 255));
        btnRemoveToy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRemoveToy.setText("-");
        btnRemoveToy.addActionListener(this::btnRemoveToyActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtToy, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearchToy, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTax, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddToy, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemoveToy, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtToy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchToy)
                    .addComponent(btnAddToy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemoveToy))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sale Date", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Date:");

        txtDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDate.setEnabled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDate, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Number of Bill", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("N°:");

        txtBillNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBillNumber)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtBillNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout imgSales1Layout = new javax.swing.GroupLayout(imgSales1);
        imgSales1.setLayout(imgSales1Layout);
        imgSales1Layout.setHorizontalGroup(
            imgSales1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        imgSales1Layout.setVerticalGroup(
            imgSales1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imgSales1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(imgSales1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCustomerActionPerformed
        // TODO add your handling code here:
        DlgCustomer dialog = new DlgCustomer(this, true);
    
        // Aquí implementamos la interface "al vuelo"
        dialog.setSelectionListener((Object obj) -> {
            E_Customer c = (E_Customer) obj;
            // Llenamos los campos en el formulario de ventas
            txtCustomerCode.setText(String.valueOf(c.getId()));
            txtCustomer.setText(c.getFirstName() + " " + c.getLastName());
        });

        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnSearchCustomerActionPerformed

    private void btnSearchToyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchToyActionPerformed
        // TODO add your handling code here:
        DlgToy dialog = new DlgToy(this, true);
    
        // Aquí implementamos la interface "al vuelo"
        dialog.setSelectionListener((Object obj) -> {
            E_Toy t = (E_Toy) obj;
            
            selectedToyId = t.getId();
            
            // Llenamos los campos en el formulario de ventas
            txtToy.setText(t.getDescription());
            txtPrice.setText(String.valueOf(t.getSalePrice()));
            txtStock.setText(String.valueOf(t.getStock()));
            txtQuantity.setText("1"); // poner 1 por defecto
            txtTax.setText("15");     // ISV de Honduras por defecto (15%)
        });

        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnSearchToyActionPerformed

    private void btnAddToyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToyActionPerformed
        // TODO add your handling code here:
        // 1. Validaciones iniciales
        if (selectedToyId == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un juguete.");
            return;
        }

        int filaExistente = -1;
        // 2. BUSCAR si el ID ya está en la tabla (Columna 0)
        for (int i = 0; i < tblCart.getRowCount(); i++) {
            int idEnTabla = Integer.parseInt(tblCart.getValueAt(i, 0).toString());
            if (idEnTabla == selectedToyId) {
                filaExistente = i; // Guardamos el índice de la fila encontrada
                break;
            }
        }
        
        // 3. Obtener y validar valores de los campos de texto
        double precio = Double.parseDouble(txtPrice.getText());
        double porcentajeIsv = Double.parseDouble(txtTax.getText());
        int cantidadNueva;
        int stockActual;

        // Usamos un bloque try-catch por si el usuario escribe letras por accidente
        try {
            cantidadNueva = Integer.parseInt(txtQuantity.getText());
            stockActual = Integer.parseInt(txtStock.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor ingrese un número entero válido para la cantidad.", "Error de entrada", JOptionPane.ERROR_MESSAGE);
            return; // Detiene la ejecución para que no ocurra un desastre
        }

        // Validar que no sea 0 o negativo
        if (cantidadNueva <= 0) {
            JOptionPane.showMessageDialog(this, "La cantidad a vender debe ser al menos 1.", "Cantidad Inválida", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validar que no estemos vendiendo más de lo que hay en bodega
        if (cantidadNueva > stockActual) {
            JOptionPane.showMessageDialog(this, "No hay suficiente inventario. Solo tienes " + stockActual + " en stock.", "Stock Insuficiente", JOptionPane.WARNING_MESSAGE);
            return;
        }

        double subTotalFila = precio * cantidadNueva;
        double isvFila = subTotalFila * (porcentajeIsv / 100.0);

        if (filaExistente != -1) {
            // --- CASO A: EL JUGUETE YA ESTÁ EN LA TABLA ---
            // Simplemente actualizamos los valores de esa fila específica
            cart.setValueAt(cantidadNueva, filaExistente, 3); // Columna Cantidad
            cart.setValueAt(isvFila, filaExistente, 4);      // Columna ISV
            cart.setValueAt(subTotalFila, filaExistente, 5); // Columna Sub-Total
        } else {
            // --- CASO B: ES UN JUGUETE NUEVO ---
            Object[] fila = new Object[6];
            fila[0] = selectedToyId;
            fila[1] = txtToy.getText();
            fila[2] = precio;
            fila[3] = cantidadNueva;
            fila[4] = isvFila;
            fila[5] = subTotalFila;
            cart.addRow(fila);
        }

        // 4. Limpiar campos y recalcular
        clearToyFields(); // Método auxiliar para vaciar txtToy, txtPrice, etc.
        calculateTotals();
    }//GEN-LAST:event_btnAddToyActionPerformed

    private void btnLeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeaveActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnLeaveActionPerformed

    private void btnRemoveToyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveToyActionPerformed
        // TODO add your handling code here:
        // 1. Obtener la fila seleccionada
        int filaSeleccionada = tblCart.getSelectedRow(); // Cambia tblCart por el nombre de tu tabla

        // 2. Verificar si hay una fila seleccionada (si no hay, devuelve -1)
        if (filaSeleccionada >= 0) {
            // 3. Eliminar la fila del modelo
            cart.removeRow(filaSeleccionada);

            // 4. Recalcular los totales para que se actualicen las cajas de texto de abajo
            calculateTotals();
        } else {
            // Si no seleccionó nada, le avisamos sutilmente (opcional)
            JOptionPane.showMessageDialog(this, "Seleccione un producto de la tabla para quitarlo.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnRemoveToyActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        // ==========================================
        // 1. VALIDACIONES
        // ==========================================
        // Asumiendo que txtCustomerCode es donde guardaste el ID del cliente y txtBillNumber el número de factura
        if (txtCustomerCode.getText().isEmpty() || txtBillNumber.getText().isEmpty() || txtDate.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, complete los datos del cliente y el número de factura.");
            return;
        }

        if (tblCart.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "El carrito está vacío. Agregue al menos un producto.");
            return;
        }

        // ==========================================
        // 2. GUARDAR EL MAESTRO (Sales)
        // ==========================================
        E_Sale sale = new E_Sale();
        sale.setNumberOfBill(txtBillNumber.getText());
        sale.setCustomerId(Integer.parseInt(txtCustomerCode.getText()));
        sale.setUserId(loggedUser.getId()); 

        // Convertir el texto de la fecha (ej. "2026-04-10") a java.sql.Date
        try {
            sale.setSaleDate(java.sql.Date.valueOf(txtDate.getText())); 
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, "Formato de fecha inválido.");
            return;
        }

        F_Sale factorySales = new F_Sale();
        int idVentaGenerado = factorySales.insert(sale); // Recordamos que este método retorna el ID

        // ==========================================
        // 3. GUARDAR LOS DETALLES (Sales_Details)
        // ==========================================
        if (idVentaGenerado > 0) {
            F_SaleDetail factoryDetails = new F_SaleDetail();
            boolean erroresEnDetalles = false;

            // Recorremos la tabla fila por fila
            for (int i = 0; i < tblCart.getRowCount(); i++) {
                E_SaleDetail detalle = new E_SaleDetail();

                // Asignamos el ID de la factura que acabamos de crear
                detalle.setSaleId(idVentaGenerado); 

                // Extraemos los datos de la fila actual (Asegúrate de que los índices coincidan con tu modelo)
                // Índice 0: Toy ID | Índice 2: Price | Índice 3: Quantity
                detalle.setToyId(Integer.parseInt(tblCart.getValueAt(i, 0).toString()));
                detalle.setPrice(Double.parseDouble(tblCart.getValueAt(i, 2).toString()));
                detalle.setQuantity(Integer.parseInt(tblCart.getValueAt(i, 3).toString()));

                // Guardamos el detalle en la base de datos
                if (!factoryDetails.insert(detalle)) {
                    erroresEnDetalles = true;
                }
                
                int toyId = Integer.parseInt(tblCart.getValueAt(i, 0).toString());
                int quantitySold = Integer.parseInt(tblCart.getValueAt(i, 3).toString());
                        
                // Actualizar cantidad
                F_Toy factory = new F_Toy();
                factory.updateStock(toyId, quantitySold);
            }

            if (!erroresEnDetalles) {
                JOptionPane.showMessageDialog(this, "¡Venta registrada con éxito!");
                resetSaleForm(); // Método para limpiar todo (ver abajo)
            } else {
                JOptionPane.showMessageDialog(this, "Venta guardada, pero hubo errores en algunos detalles.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Error de conexión al registrar la factura.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void tblCartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCartMouseClicked
        // TODO add your handling code here:
        int fila = tblCart.getSelectedRow();
        if (fila >= 0) {
            // 1. Recuperamos el ID y lo guardamos en la variable global
            selectedToyId = Integer.parseInt(tblCart.getValueAt(fila, 0).toString());

            // 2. Llenamos los campos de texto con los datos de la fila
            txtToy.setText(tblCart.getValueAt(fila, 1).toString());
            txtPrice.setText(tblCart.getValueAt(fila, 2).toString());
            txtQuantity.setText(tblCart.getValueAt(fila, 3).toString());
            txtTax.setText("15");

            // Consultamos la base de datos para obtener el stock más reciente
            F_Toy factory = new F_Toy();
            E_Toy toyData = factory.getToy(selectedToyId);

            if (toyData != null) {
                txtStock.setText(String.valueOf(toyData.getStock()));
            }
        }
    }//GEN-LAST:event_tblCartMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToy;
    private javax.swing.JButton btnLeave;
    private javax.swing.JButton btnRemoveToy;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearchCustomer;
    private javax.swing.JButton btnSearchToy;
    private logicLayer.ImgSales imgSales1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCart;
    private javax.swing.JTextField txtBillNumber;
    private javax.swing.JTextField txtCustomer;
    private javax.swing.JTextField txtCustomerCode;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtResultTax;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtTax;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtToy;
    private javax.swing.JTextField txtWorker;
    // End of variables declaration//GEN-END:variables
}
